export const countryCodes = [
  { name: "India", dial_code: "+91" },
  { name: "United States", dial_code: "+1" },
  { name: "United Kingdom", dial_code: "+44" },
  { name: "Australia", dial_code: "+61" },
  { name: "Canada", dial_code: "+1" },
  { name: "New Zealand", dial_code: "+64" },
  { name: "Singapore", dial_code: "+65" },
  { name: "United Arab Emirates", dial_code: "+971" },
  { name: "Saudi Arabia", dial_code: "+966" },
  { name: "Germany", dial_code: "+49" },
  { name: "France", dial_code: "+33" },
  { name: "Netherlands", dial_code: "+31" },
  { name: "Italy", dial_code: "+39" },
  { name: "Spain", dial_code: "+34" },
  { name: "Switzerland", dial_code: "+41" },
  { name: "Sweden", dial_code: "+46" },
  { name: "Norway", dial_code: "+47" },
  { name: "Denmark", dial_code: "+45" },
  { name: "Ireland", dial_code: "+353" },
  { name: "South Africa", dial_code: "+27" },
  { name: "Japan", dial_code: "+81" },
  { name: "South Korea", dial_code: "+82" },
  { name: "China", dial_code: "+86" },
  { name: "Malaysia", dial_code: "+60" },
  { name: "Thailand", dial_code: "+66" },
  { name: "Indonesia", dial_code: "+62" },
  { name: "Philippines", dial_code: "+63" },
  { name: "Brazil", dial_code: "+55" },
  { name: "Mexico", dial_code: "+52" },
  { name: "Turkey", dial_code: "+90" },
];
